# Generated by Django 3.1.5 on 2021-10-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('subContent', models.TextField()),
                ('slug', models.SlugField()),
                ('categary', models.CharField(max_length=50)),
                ('subCategary', models.CharField(max_length=50)),
                ('pubDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
