# Generated by Django 3.1.5 on 2021-10-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImg',
            field=models.ImageField(default='', upload_to='ShopBlog/media'),
        ),
    ]
