# Generated by Django 3.1.5 on 2021-10-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopBlog', '0002_post_postimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
