# Generated by Django 3.1.5 on 2021-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopBlog', '0003_auto_20211014_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subContent',
            field=models.TextField(max_length=200),
        ),
    ]
